### ISSUE TITLE
Index page with presentations names and links

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/clickhouse-presentations#5]
Single page listing all presentations with clickable link to presentation itself and to YouTube recording (if avaliable)

**Comment by blinkov** [comment]
It'd better be part of official website, used to be on my todo, but couldn't find a time slot to implement.

**Comment by filimonov** [comment]
Maybe let's try to do it incrementally (See #6 )? And i think we can have 'master copy' here (easier to maintain: single place) and a copy on a website?
