### ISSUE TITLE
parseDateTime minutes:seconds.fraction

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/clickhouse-presentations#59]
ClickHouse 23.8.2.7 LTS

```sql
SELECT parseDateTime('01:16.520000', '%i:%s.%f')
```

VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE (expected 76.52)

I am trying to parse the string into a fractional duration (in seconds), so not really a DateTime type, but I did not find a suitable parsing function

**Comment by tavplubix** [comment]
Please create an issue in https://github.com/ClickHouse/ClickHouse
