### ISSUE TITLE
 want PDF edition

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/clickhouse-presentations#7]
>Could you provide a PDF edition for the following links ？
https://github.com/ClickHouse/clickhouse-presentations/blob/master/meetup49/roadmap/index.html
https://github.com/ClickHouse/clickhouse-presentations/blob/master/meetup50/new_features/index.html
the PDF edition is very convenient for the readonly user.

**Comment by alexey-milovidov** [comment]
[ClickHouse Roadmap 2021.pdf](https://github.com/ClickHouse/clickhouse-presentations/files/5939709/ClickHouse.Roadmap.2021.pdf)
[ClickHouse Features 2021.pdf](https://github.com/ClickHouse/clickhouse-presentations/files/5939710/ClickHouse.Features.2021.pdf)

**Comment by alexey-milovidov** [comment]
How to make pdf:

1. Open presentation in Chromium-based browser, example: https://presentations.clickhouse.tech/meetup50/new_features/
2. In menu, select "Print". Select "Print to PDF".
