### ISSUE TITLE
Cross-platform file names

### ISSUE THREAD

**Issue by Stan-RED** [ClickHouse/clickhouse-presentations#71]
It's not a good idea to use colons in file names like it is in 69978ad5229c00d2629bf0f31e3f6ffb265c00d7. It's impossible to clone in Windows, for example.

**Comment by alexey-milovidov** [comment]
We cannot rename these files after they are published (to avoid broken links).

We have the same problem in the main repository:

```
 create mode 100644 tests/queries/0_stateless/data_minio/::03215_archive.csv
 create mode 100644 tests/queries/0_stateless/data_minio/test.zip::03215_archive.csv
 create mode 100644 tests/queries/0_stateless/data_minio/test::03215_archive.csv
```

It is too late to correct this error.

For Windows, I recommend creating a Linux VM, using WSL, ssh to a Linux machine, installing Linux for dual boot, buying a separate machine with Linux, or not cloning this repository.
